language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  app: rocky-lowlands-67751
  api_key:
    secure: dWOR9/MRxz4GQOvBQWYaJod1IlD4ItUoH7lZ3/lpc3CrlLhAoGN8274cJcDQCdytZY3ynDPWG6BNvgqUrFxvsIcsmDWLfiWABQRwSKGFzzAQqFyCf22ICs24il4vSNhN7iTaddIoDNjbX9jUJZYBkzBxm7xhYJxDZ5ltiN1nA2e5vQ/Jk2EdKrNNgcT/iRTkL7QKtnuLhxXp4z2z+9iAQT36OFz20czbZButazGS4l3bySckJ90v/N25TFDOYfn9jC2UbQTQCyvCE+gOxlM1WdtE94wjmVl76rwuTcAGFD9kKP3Cim/SpOmNRsslbclSsaR7Xdjyu9fcaz0daacfbmZRCLZd9aJMjR+AV24rS3cyp0VXrujbQpfsLlpCKTaBfZaBHZtxq1w1aveX5H2ce3GC4bVEcw5Ce5s8whQ24F3YMOA3e40FyxH1vO0xogsxwhhZnM3ePm8QMkt1AmHQa4d9FpIt7sg2Xpe+nF26J6lXL3BWLi30vzQ6uLHn2haJLu1CDP7PV/4NWngffoJDIQyE3b2JNLgT+2p8dGgRRi9cp24olOKoWJbXE9/bM7fJvioooRf0DVQqLOclHeHvvZvDwBWmJ0j4ix0mQkailayzmKdLNKdVInJZZfJb6l7EJLXkRRvjdaK6zd+HBY/LPaCGo5UnTwSIDcTEuejzvRk=
