# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9db1b5a825c872efd535e460f2f47aa5b880346cfb5e320e9b45095ea69ca2324d5e1f90bceabe4815f01913e7f81bc1a816707d0b7c9f4c66d9e1b168a5d270

test:
  secret_key_base: 739189159b347df0e75c61b76bda7f688185bf718097b5f1583504985cecd25b90aa966715deb50be00cd90bdb6eb42bee4b1baa9163d31c3c9c5ab1fa26a158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
